### PR TITLE
Added 6 Speakers

### LINKED ISSUE #323: Add speakers Kamesh Sampath, Suraj Narwade, and Aayush Arora
Kamesh Sampath 
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
image

Suraj Narwade 
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
image

Aayush Arora
His info is on https://eventyay.com/e/b548bcfc/#speakers
The photo's quality is bad.

### PR DESCRIPTION
**Pull request by rishabh19038**
Fixes #323 #324

Added Speakers: Kamesh Sampath, Suraj Narwade, Aayush Arora, Pronnoy Goswami, Himanshu Singh.
Modified image of Speaker: Harshit Dwivedi in 300x300 dimensions.

Preview: https://adg-vit.github.io/2018.fossasia.org/

### CODE REVIEW

**Comment by rishabh19038** [comment]
@simsausaurabh @duttaditya18 @gautamjajoo Could you please review this PR. I messed up the previous PR #363 while squashing the commits. Sorry for the inconvenience.

**Comment by mariobehling** [comment]
Please find more suitable pictures for Aayush and Harshit: No street photos, no holiday photos, conservative conference photos! Avoid backlight, other people in the photo etc. @the-dagger

**Comment by the-dagger** [comment]
@rishabh19038 try this image of mine.

https://imgur.com/gallery/AnSdH

Best!

**Comment by rishabh19038** [comment]
@the-dagger Thanks! Made the changes.

**Pull request merged**
