### PR TITLE
Improve dropdown menu:

### PR DESCRIPTION
**Pull request by mani87**
Dropdown menu is improved
by adding hovering effect
to it and change of text color
while hover.

Closes https://github.com/fossasia/2018.fossasia.org/issues/58

### CODE REVIEW

**Comment by mani87** [comment]
screenshot_20170917_234732

**Comment by mani87** [comment]
@mariobehling can you please take a look at it?
Thankyou :)

**Comment by vibhcool** [comment]
@mani87, please fix the conflict issue

**Comment by mariobehling** [comment]
Closing due to inactivity.

**Pull request closed without merging**
