### PR TITLE
Add speaker Calvin Cheng

### LINKED ISSUE #303: Add speaker Calvin Cheng
Please use his info from eventyay https://eventyay.com/e/b548bcfc/#speakers

### PR DESCRIPTION
**Pull request by ritikamotwani**
Speaker Calvin Cheng added.
Fixes #303 
Link: https://ritikamotwani.github.io/2018.fossasia.org/

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@ritikamotwani please provide preview link

**Comment by hpdang** [comment]
@ritikamotwani please resolve the conflict

**Comment by ritikamotwani** [comment]
@hpdang  @CosmicCoder96  I have resolved the conflicts.

**Comment by ritikamotwani** [comment]
@mariobehling please review.

**Pull request merged**
