### PR TITLE
Fixed #329, #330, #331, #332, #333 - Add Speakers

### LINKED ISSUE #329: Add speakers Chetankumar Khatri, Masayuki Igawa, and Sagar Hani
Info on https://eventyay.com/e/b548bcfc/#speakers

Chetankumar Khatri
There is the photo:
image

Masayuki Igawa 
There is the photo:
image

Sagar Hani 
His photo on the webpage is in a circular shape, and there is no high-quality photo on Google.

### PR DESCRIPTION
**Pull request by rishabh19038**
Fixes #329 #330 #331 #332 #333

Speakers Added:
Masayuki Igawa, Sagar Hani, Daniel Pocock, Adarsh S, Jens Petersen, Dilpreet Singh, Janki Chhatbar, Le Kien Truc, Brian Proffitt, Alex Shinn, Himanshu Dixit, Chandan Kumar

Speakers Modified: 
Chetankumar Khatri, Saptak Sengupta, Kushal Das

Preview: https://adg-vit.github.io/2018.fossasia.org/

### CODE REVIEW

**Comment by rupav** [comment]
screenshot 2018-01-27 22 23 43
Sorry, approved by mistake, shift last to images to left of the page instead to right, see original site as reference.

**Comment by rishabh19038** [comment]
@rupav fixed

**Comment by rupav** [comment]
@rishabh19038 please squash your commits too.
@hpdang please review and merge.

**Comment by rishabh19038** [comment]
@rupav squashed

**Comment by hpdang** [comment]
@rishabh19038  could you please make the final changes below:

* Take out Himanshu Dixit, Janki Chhatbar for now (we are getting a new photo of them)

* Change photo of Jens (drop to the right ratio to this face)
jenspetersen


* Include job title of the following speakers: 
Brian Proffitt
‎Principal Program Manage
Red Hat

**Comment by rishabh19038** [comment]
@hpdang Suggested changes have been made.
Preview: https://adg-vit.github.io/2018.fossasia.org/

**Comment by hpdang** [comment]
@rishabh19038 awesome, thank you!

**Pull request merged**
