### PR TITLE
Fixed #306 - Dropdown background color

### LINKED ISSUE #306: Fix the Drop-down background color
screen shot 2018-01-26 at 5 25 57 pm

### PR DESCRIPTION
**Pull request by rishabh19038**
Fixes #306

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@rishabh19038 please provide preview link.

**Comment by rishabh19038** [comment]
@simsausaurabh 

Initially -
initial

After Fix -
screen shot 2018-01-26 at 6 00 35 pm

**Comment by rishabh19038** [comment]
Here's the preview link:
https://rishabh19038.github.io/2018.fossasia.org/

**Comment by rishabh19038** [comment]
@simsausaurabh As directed, font color has been changed to black from start.

**Comment by rishabh19038** [comment]
Preview Link:
https://rishabh19038.github.io/2018.fossasia.org/

**Comment by rishabh19038** [comment]
@simsausaurabh Squashed.

**Comment by rishabh19038** [comment]
@hpdang please review and close the issue #306  if everything is good. 😄

**Comment by mariobehling** [comment]
This has been caused by a recent commit, that should not have touched the CSS. I fixed it now as desired. Cheers.

**Pull request closed without merging**
