### PR TITLE
Design of dropdown in nav bar

### LINKED ISSUE #58: bad hover effect for navigation bar- dropdown menu

### PR DESCRIPTION
**Pull request by parimatrix**
Fixes #58 @AshishkrGoyal Adds a design change to the dropdown menu of nav bar.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please provide a screenshot and link to a test page. Thank you.

**Comment by parimatrix** [comment]
Sorry for not providing that earlier. 
https://parimatrix.github.io/2018.fossasia.org/

screenshot 18

**Comment by mariobehling** [comment]
On the dropdown there is also a space above "FOSSASIA Labs". Please avoid this additional space.

**Comment by parimatrix** [comment]
A minor 2px of space is kind of necessary, which was pre-added to separate it from the header. Thanks!

**Comment by mariobehling** [comment]
Thank you!

**Pull request merged**
