### PR TITLE
Fixes #120 :Fixed bugged icon link and Added more icons

### LINKED ISSUE #120: Bugged Icons(Incorrect and Incomplete Icons)

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #120

### CODE REVIEW

**Comment by saarthakchats** [comment]
https://saarthakchats.github.io/suparifuryie2018.fossasia.org/

**Comment by saarthakchats** [comment]
@sayak119 Can we also merge?

**Comment by saarthakchats** [comment]
@vaibhavsingh97

**Comment by saarthakchats** [comment]
@gabru-md
@anshumanv

**Comment by duttaditya18** [comment]
icon fa fa-google-plus

**Comment by duttaditya18** [comment]
Instead of using the old Google Plus Logo.

Use `icon fa fa-google-plus`.

**Comment by saarthakchats** [comment]
@duttaditya18

**Comment by arjunpandey2003** [comment]
LGTM!

**Comment by arjunpandey2003** [comment]
Provide a description of the changes made in the PR description

**Comment by duttaditya18** [comment]
@saarthakchats Looks good!

**Comment by saarthakchats** [comment]
Thanks @gabru-md @duttaditya18 @arjunpandey2003

**Comment by saarthakchats** [comment]
@vaibhavsingh97 @anshumanv @gabru-md 
Can you guys please do something about merging this, my task has been lying for quite some time now. Can you request @mariobehling to merge.

**Comment by saarthakchats** [comment]
Thanks @mariobehling

**Pull request merged**
