### PR TITLE
Fixed Style and layout bugs

### LINKED ISSUE #129: Style and layout bugs on home page
1. Speaker images not in uniform size #125 
image 
2. Social-links not properly aligned
image
3. Layout bugs in featured speakers section
image

I am fixing all these issues and will soon put up a PR.

### PR DESCRIPTION
**Pull request by samyukthacodes**
Fixes #129 #125 
Preview available at https://samyukthacodes.github.io/2018.fossasia.org/

### CODE REVIEW

**Comment by samyukthacodes** [comment]
@mariobehling Please review this PR and merge.

**Comment by rishiraj824** [comment]
@samyukthacodes Please remove the conflicts as indicated. Thanks!

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by samyukthacodes** [comment]
@mariobehling  @rishiraj824 Resolved conflicts.

**Comment by samyukthacodes** [comment]
@mariobehling Can you please merge?

**Comment by samyukthacodes** [comment]
@mariobehling @hpdang Can anyone please merge quickly? I've to take up more tasks.

**Comment by samyukthacodes** [comment]
@mariobehling @hpdang Can you please merge? I've only hours left.

**Comment by samyukthacodes** [comment]
@mariobehling @hpdang Can you please merge? I've been waiting for so long. I've to take up more tasks.

**Pull request merged**
