### PR TITLE
Fixed #180

### LINKED ISSUE #180: Update profile picture and job title of  speakers Nan Xiao, Matt Ranostay, Mai-Hsuan Chia
Replace the current photo and job title with the following 

1. Nan Xiao >> Research Engineer - Data Storage Institute
Use the new picture from https://eventyay.com/e/b548bcfc/#speakers

2. Matt Ranostay >> Senior Software Engineer - Konsulko Group
Use the new picture from https://eventyay.com/e/b548bcfc/#speakers

3. Mai-Hsuan Chia  >> Developer - Ethereum Research
Use the new picture from https://eventyay.com/e/b548bcfc/#speakers

### PR DESCRIPTION
**Pull request by achiv**
Updated photos and job titles as mentioned.
Do mention if changes are required.

<a href="https://achiv.github.io/2018.fossasia.org/">Preview Link</a>

### CODE REVIEW

**Comment by hpdang** [comment]
@achiv what i see frm the preview

screenshot from 2018-01-19 01-52-17

**Comment by achiv** [comment]
@hpdang Preview corrected. Please have a look

**Comment by achiv** [comment]
@hpdang Correction made. Please have a look again.

**Comment by simsausaurabh** [comment]
Provide preview link, squash your commits. @achiv

**Comment by hpdang** [comment]
@achiv thank you!!!

**Pull request merged**
