### PR TITLE
Adding two new speakers Alisha Aneja and Daren Frankel

### PR DESCRIPTION
**Pull request by minibhati93**
Added two speakers

### CODE REVIEW

**Comment by hpdang** [comment]
@minibhati93 please provide preview link

**Comment by minibhati93** [comment]
@hpdang Could be please point to the repo or guidelines which I can follow for creating the preview link?

**Comment by hpdang** [comment]
@gautamjajoo please help @minibhati93 and to resolve this conflict too

**Comment by gautamjajoo** [comment]
@minibhati93 You can go to Settings section fo your repository and set up the GithubPages. and send the preview website link here.

**Comment by minibhati93** [comment]
The preview link is done. Working on the conflict now
[Preview link](https://minibhati93.github.io/2018.fossasia.org/)

**Comment by hpdang** [comment]
@minibhati93 on eventyay there's also LinkedIn URL, github URL, please include whatever you can see on eventyay. Thank you.

**Comment by minibhati93** [comment]
@simsausaurabh There was a conflicting repo with an existing cname in my branch which was preventing me to generate the preview link. So, I was trying to resolve the conflict and in that attempt the cname got deleted from my branch.

**Comment by naveentherocker** [comment]
@minibhati93 Add the CNAME and keep it as it was there.

**Comment by naveentherocker** [comment]
@minibhati93 Add the CNAME and keep it as it was there.

**Comment by gautamjajoo** [comment]
@minibhati93 I would suggest revert the changes and copy the same code once more.

**Comment by hpdang** [comment]
I'm closing this, waiting too long to resolve the conflict. We already fixed this issue.

**Pull request closed without merging**
