### PR TITLE
Sarthakprajapati Replace photo of Prasad Pandit  #264

### PR DESCRIPTION
**Pull request by sarthakprajapati**
#264 Replace photo of Prasad Pandit 
#255 Replace photo of speaker Chetan Khatri

### CODE REVIEW

**Comment by hpdang** [comment]
@sarthakprajapati please also provide preview link

**Comment by sarthakprajapati** [comment]
https://ibb.co/cm9Fyb
screenshot from 2018-01-23 19-02-52

**Comment by realslimshanky** [comment]
@sarthakprajapati please update your description with the mention of the issue which you are trying to solve.

**Comment by sarthakprajapati** [comment]
Done!

**Comment by hpdang** [comment]
@sarthakprajapati great, thank you!

**Comment by hpdang** [comment]
@sarthakprajapati cld you check, look like Prasad image is bit wrongly resize

**Pull request closed without merging**
