### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by tanya-vedi**

### CODE REVIEW

**Comment by tanya-vedi** [comment]
#168

**Comment by simsausaurabh** [comment]
Please provide deployment link.

**Comment by tanya-vedi** [comment]
image
Speaker removed

**Comment by tanya-vedi** [comment]
Done

**Comment by realslimshanky** [comment]
There still seem to be some problem. Make sure you are rebasing properly.

**Comment by tanya-vedi** [comment]
Lemme know if there's still some issue.

**Comment by nityanandagohain** [comment]
@tanya-vedi you are still having conflicts please merge new commits and update you branch.

**Comment by realslimshanky** [comment]
@tanya-vedi there are still conflicts in your branch. Could you please share the steps you are followings in order to help you better.

**Comment by tanya-vedi** [comment]
I resolve the conflicts and then I see that "no more conflicts, branch ready to merge". After sometime however, I get to see it still has conflicts. Should I submit new PR now?

**Comment by realslimshanky** [comment]
@tanya-vedi no need to create a new PR, we can fix this one. Let me get back to you.

**Comment by tanya-vedi** [comment]
Fixes #168

**Comment by mariobehling** [comment]
Issue and description is missing. Please help reviewers by providing sufficient info in PRs. Closing it therefore. Please submit a new PR following best practices. Cheers.

**Pull request closed without merging**
