### PR TITLE
Change section-header background-image for darker fixes #91

### LINKED ISSUE #91: Text not readable in one section
## Issue
In the section **A little more about the FOSSASIA Summit** text is not readable since its white and image is light. 

## How to solve it?
Add semi transparent dark layer to the image or section

## Would you like to work on it?
Sure!

bug4_2018_new

### PR DESCRIPTION
**Pull request by kubami9**
Change section-header background-image for darker to add contrast and make white text readable.

Preview link: https://kubami9.github.io/2018-kubamichalski-foss-contributing/

### CODE REVIEW

**Comment by kubami9** [comment]
@mariobehling okay I'll fix it

**Comment by kubami9** [comment]
@mariobehling done 😄

**Comment by mariobehling** [comment]
Good job! Would you be interested to help with this issue? https://github.com/fossasia/publiccode.asia/issues/68

**Comment by kubami9** [comment]
Sure 😄

**Pull request merged**
