### PR TITLE
Fix #352: Speakers images not horizontally aligned and some images out of flow

### LINKED ISSUE #352: Speakers images not horizontally aligned
In the "Speakers" section, the first two images aren't horizontally aligned for browser's screen width b/w 638px & 767px

iss1

Browser: Chrome
OS: Windows 8.1

### PR DESCRIPTION
**Pull request by apooravc**
Fixes #352 
Preview: https://apooravc.github.io/2018.fossasia.org/

### CODE REVIEW

**Comment by apooravc** [comment]
@sayak119 Squashed to one but there was a conflict afterwards so had to commit another.

**Comment by apooravc** [comment]
@mengjiann Please compare https://apooravc.github.io/2018.fossasia.org/ and https://2018.fossasia.org/ for first two speaker images with browser screen width b/w 638px & 767px. I see the issue resolved.

**Comment by mengjiann** [comment]
Seems like no issue on my end anymore. Can you double check?

My user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

Ipad 768x1024

screen shot 2018-02-11 at 11 04 25 pm

640 x 767

image

**Comment by apooravc** [comment]
@mengjiann I'm not sure about the lower limit of the range but I checked again and I still see the misalignment just below 768px of screen width in Chrome v64 at https://2018.fossasia.org/
Preview:
img

**Comment by mariobehling** [comment]
Closing due to inactivity. Please open a new PR, if you would like to follow up. Thank you.

**Pull request closed without merging**
