### PR TITLE
Fixed #192: 'Remove Speaker Wei Shan Ang'

### LINKED ISSUE #192: Remove Speaker Wei Shan Ang
Speaker Wei Shan Ang is not able to join, please remove him.

### PR DESCRIPTION
**Pull request by simsausaurabh**
Fixes: #192 
Preview link: https://simsausaurabh.github.io/2018.fossasia.org/
@hpdang Please review. Thanks.

### CODE REVIEW

**Comment by hpdang** [comment]
@simsausaurabh please take out 'TBA' for Dr Chong Shang Shan

**Comment by simsausaurabh** [comment]
@hpdang okay, but due to empty <span></span> for Dr Chong Shang Shan leads to the improper alignment among other speakers. If there is any other content which can be filled into that please suggest, or I remove that.

**Comment by simsausaurabh** [comment]
It's due to already built structure of section for speakers. Here is an attachment showing empty span tag for Dr Chong Shang shan:

screenshot from 2018-01-21 12-39-19

**Comment by hpdang** [comment]
@simsausaurabh I dont understand what you mean. We just don't include Chong's company

**Comment by simsausaurabh** [comment]
@hpdang please review. 
Thanks :)

**Pull request merged**
