### PR TITLE
Added Speakers -Ahmed Syed, Alyssa Ong, Chris Auld

### LINKED ISSUE #439: Add speakers Ahmed Syed, Alyssa Ong, Chris Auld
Please take their info from here https://eventyay.com/e/b548bcfc/#speakers

And use photos below
Ahmed Syed
bio pic

Alyssa Ong
unnamed 1

Chris Auld
image001 1

### PR DESCRIPTION
**Pull request by gautamjajoo**
Fixes #439 .
Preview Link :- https://gautamjajoo.github.io/FossasiaEvent2018/
@hpdang @edenyay

### CODE REVIEW

**Comment by gautamjajoo** [comment]
@edenyay A shorter job title for CHris Auld.

**Comment by edenyay** [comment]
@gautamjajoo Let's try Technical Evangelist Manager for now. If there's feedback from the speaker, we can think of another way. thank you!

**Comment by gautamjajoo** [comment]
@edenyay Ok! will update the PR.

**Comment by hpdang** [comment]
@gautamjajoo can you fix it?

**Pull request merged**
