### PR TITLE
Removed Loi Luu, Ahmed Syed and German Saprykin from the speakers section

### PR DESCRIPTION
**Pull request by rak-shit**

### CODE REVIEW

**Comment by rak-shit** [comment]
Done!

**Comment by akshatnitd** [comment]
@rak-shit Please squash the commits and finalise the PR.

**Comment by abishekvashok** [comment]
@akshatnitd pls use the squash and merge option

**Comment by utkarshnag** [comment]
I squashed his commits and made a seperate PR referencing the issue if it helps.

**Pull request merged**
