### PR TITLE
Fix alignment of twitter bird

### PR DESCRIPTION
**Pull request by MadhavBahlMD**
This is for issue #347 Position of twitter bird
Fixed alignment
image

### CODE REVIEW

**Comment by MadhavBahlMD** [comment]
Fixed the footer sizing #349

**Comment by MadhavBahlMD** [comment]
Fixed issue #350 
The text was being hidden by the bullet points. Now it's fixed

**Comment by MadhavBahlMD** [comment]
image

**Comment by MadhavBahlMD** [comment]
preview link as in? 
(I have attached the screenshots)

**Comment by MadhavBahlMD** [comment]
Here you go,
https://madhavbahlmd.github.io/2018.fossasia.org/


### Changes made:


1. alignment of twitter bird and text
image

2. Footer sizing
image


3. Text hidden by bullet points (Fixed)
image


Thanks :)

**Comment by MadhavBahlMD** [comment]
Thanks @daminisatya 
I have squashed all the commits

**Comment by MadhavBahlMD** [comment]
#348 #349 #350 Are fixed and the commits are squashed, 
wou can consider merging it :)

**Comment by mariobehling** [comment]
Should not be changed.

**Pull request closed without merging**
