### PR TITLE
Add speaker Tiejun Chen 

### PR DESCRIPTION
**Pull request by sarthakprajapati**

### CODE REVIEW

**Comment by realslimshanky** [comment]
@sarthakprajapati you can ask here if you are facing any problem with the PR. It's better to fix the existing one since you already have worked on it. All it needs is few changes.

**Comment by sarthakprajapati** [comment]
Sir I was having problem in using github. Now i am working on it by watching video lectures over YouTube! Hoping for good!

On 24-Jan-2018 8:07 PM, Shashank Kumar <notifications@github.com> wrote:

@sarthakprajapati<https://github.com/sarthakprajapati> you can ask here if you are facing any problem with the PR. It's better to fix the existing one since you already have worked on it. All it needs is few changes.

**Comment by realslimshanky** [comment]
@sarthakprajapati you can ask your problem here as well I would be happy to help you out.
ps: please drop the sir, we are all learning from one another here :blush:

**Comment by sarthakprajapati** [comment]
Okay 😊

On 24-Jan-2018 8:31 PM, Shashank Kumar <notifications@github.com> wrote:

@sarthakprajapati<https://github.com/sarthakprajapati> you can ask your problem here as well I would be happy to help you out.
ps: please drop the sir, we are all learning from one another here 😊

**Pull request closed without merging**
