### PR TITLE
Correct twitter link for speaker

### LINKED ISSUE #370: Correct twitter link for speaker "Sumedh Nimkarde"
Need to correct link for the speaker "Sumedh Nimkarde."

### PR DESCRIPTION
**Pull request by sumedh123**
Fixes #370 
@hpdang Please review and merge.

### CODE REVIEW

**Comment by simsausaurabh** [comment]
@sumedh123 please open issue for this and make a reference.

**Comment by mariobehling** [comment]
Resolve conflicts.

**Comment by sumedh123** [comment]
@mariobehling @simsausaurabh Done 👍

**Comment by hpdang** [comment]
@sumedh123 conflict?

**Comment by sumedh123** [comment]
@hpdang I had resolved but since someone just merged a pr, conflict has arised. removing the conflicts once again but then someone has to merge it after that.

**Comment by sumedh123** [comment]
@hpdang Please merge.

**Pull request merged**
