### PR TITLE
Add speaker Cherry G. Mathew, Sara Robinson & Duane O'Brien

### PR DESCRIPTION
**Pull request by ritikamotwani**
Speakers added.
Fixes: #343 
Link: https://ritikamotwani.github.io/2018.fossasia.org/

### CODE REVIEW

**Comment by hpdang** [comment]
@ritikamotwani thank you dear, could you help  me to make a bit of adjustment, on job tittle and company, please see below: 

Cherry G. Mathew
Cofounder
HackBeach & Hillshack

Duane O'Brien
Head of Open Source 
Indeed

**Comment by hpdang** [comment]
Please resolve conflict

**Comment by ritikamotwani** [comment]
@hpdang  please review.

**Comment by nityanandagohain** [comment]
@ritikamotwani you didnt't add social link's of Duane

**Pull request merged**
