### PR TITLE
added pooja puruswini 

### LINKED ISSUE #264: Replace photo of Prasad Pandit
pjp-fossasia

### LINKED ISSUE #265: Add speaker Tiejun Chen
tiejunchen

Please use the above photo and get his details from https://eventyay.com/e/b548bcfc/#speakers

### LINKED ISSUE #280: Add speaker Pooja Purswani
raj_7478-001

Please get her details here https://eventyay.com/e/b548bcfc/#speakers

### PR DESCRIPTION
**Pull request by nityanandagohain**
fixes #280 
fixes #264 

preview : https://nityanandagohain.github.io/2018.fossasianitya.io/

### CODE REVIEW

**Comment by nityanandagohain** [comment]
@gautamjajoo actually I have added a new photo of Prasad Pandit

**Comment by nityanandagohain** [comment]
@mariobehling please check now.

**Comment by hpdang** [comment]
@nityanandagohain his head is missing.

**Comment by nityanandagohain** [comment]
@hpdang changed but still the full head doesn’t appear.

**Pull request merged**
