### PR TITLE
Added missing social links...

### PR DESCRIPTION
**Pull request by Beta-King**
#123 I've fixed this issue...

### CODE REVIEW

**Comment by Beta-King** [comment]
https://beta-king.github.io/Beta-King2018.fossasia.org/ --> Preview Link

**Comment by Beta-King** [comment]
If there are no conflicts, can we merge ??

**Comment by Beta-King** [comment]
Can we merge now ?? :D

**Comment by Beta-King** [comment]
How much longer ??

**Comment by Beta-King** [comment]
Can we merge now ??

**Comment by Beta-King** [comment]
??

**Comment by saarthakchats** [comment]
@Beta-King this can only be merged by mario

**Comment by Beta-King** [comment]
I know; waiting for him only :D

**Comment by stealthanthrax** [comment]
@mariobehling

**Comment by Beta-King** [comment]
@mariobehling , could you please merge this PR ?? :D

**Comment by mariobehling** [comment]
Please resolve conflicts

**Pull request closed without merging**
