### PR TITLE
updated bio data of Felipe Hoffa #107

### LINKED ISSUE #107: Update Speaker's Bio - Felipe Hoffa
Under Featured Speakers Session: 

Please remove the current bio of Felipe Hoffa and add the following text: 

In 2011 Felipe Hoffa moved from Chile to San Francisco to join Google as a Software Engineer. Since 2013 he's been a Developer Advocate on big data - to inspire developers around the world to leverage the Google Cloud Platform tools to analyze and understand their data in ways they could never before. You can find him in several YouTube videos, blog posts, and conferences around the world.

### PR DESCRIPTION
**Pull request by himanish-star**
Fixes #107 
Before
image

After
changes can be previewed at https://himanish-star.github.io/2018.fossasia.org/
image

### CODE REVIEW

**Comment by hpdang** [comment]
@himanish-star please check https://2018.fossasia.org 
below is what happened 
screenshot from 2017-12-20 17 24 22

images should be aligned.

**Comment by duttaditya18** [comment]
Can you reopen this then?

**Comment by himanish-star** [comment]
@hpdang I saw just now, You can see https://himanish-star.github.io/2018.fossasia.org/ and you'll see that it works . Meanwhile I'm figuring this out

**Comment by hpdang** [comment]
@himanish-star I think you need to add extra space under Bunnie Huang's bio as well, reference https://2017.fossasia.org

**Comment by duttaditya18** [comment]
@hpdang #110 fixes this completely.

**Comment by himanish-star** [comment]
@hpdang , what I would suggest is that you do a hard reload by deleting your cache. This will do as I saw now that the custom.css is being cached

**Comment by hpdang** [comment]
@himanish-star the spacing doesn't look good, let's shorten the text. Please remove the last sentence 'You can find ....'

**Comment by himanish-star** [comment]
@hpdang , ok I'm on it

**Pull request merged**
