### PR TITLE
Speaker: Added - Chetan Khatri

### PR DESCRIPTION
**Pull request by chetkhatri**
What were proposed in this pull request ?
* Speaker added (named: Chetan Khatri) at index.html
* 300 x 300 px image has been added of speaker
How this pull request has tested ?
* Manually

Kindly review and do needful.

### CODE REVIEW

**Comment by chetkhatri** [comment]
Reviewer added: @geekyd @hpdang

**Comment by ParthS007** [comment]
@chetkhatri Can you please provide a preview link?

**Comment by chetkhatri** [comment]
@ParthS007 Sure, https://chetkhatri.github.io/2018.fossasia.org/

**Comment by hpdang** [comment]
Thanks @chetkhatri

**Pull request merged**
