### PR TITLE
Fixed a bug (Michael Downey's photo)

### PR DESCRIPTION
**Pull request by mjd220903**

### CODE REVIEW

**Comment by mjd220903** [comment]
How do I make a `deployment link` for this ???

**Comment by simsausaurabh** [comment]
Use your forked repo to publish on gh-pages and it will automatically deploy your project on GitHub and paste that link over here.

**Comment by mjd220903** [comment]
https://mjd220903.github.io/2018.fossasia.org/.

**Comment by mjd220903** [comment]
@simsausaurabh  Please reply

**Comment by mjd220903** [comment]
@simsausaurabh please merge it fast 
I have to submit my task for review on GCI

**Comment by mjd220903** [comment]
@hpdang  can you merge it as fast as you can as i have to submit it on GCI

**Comment by simsausaurabh** [comment]
@mjd220903 sorry, I'm not the maintainer of this project.

**Comment by hpdang** [comment]
@mjd220903 which bug are you referring to?

**Pull request closed without merging**
