### PR TITLE
Added Speakers

### LINKED ISSUE #322: Add speakers  Raju Koushik Gorantla, Nikhil Rayaprolu, and Harshit Prasad
Raju Koushik Gorantla
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
image

Nikhil Rayaprolu
His info is on https://eventyay.com/e/b548bcfc/#speakers
The photo's quality is bad.

Harshit Prasad
His info is on https://eventyay.com/e/b548bcfc/#speakers
This is the photo:
image

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fixes #322 
Deployment: https://2018-fossasia.surge.sh

cc: @harshit98 @RajuKoushik

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
I think they should be in normal speakers, updated it.

**Comment by hpdang** [comment]
@aashutoshrathi please resolve the conflict

**Comment by hpdang** [comment]
@aashutoshrathi can you resolve the conflict plz?

**Comment by aashutoshrathi** [comment]
Sorry for being late, was offline for a while.

**Comment by anshumanv** [comment]
Some extra changes are appearing @aashutoshrathi, please check.

**Comment by anshumanv** [comment]
@hpdang please merge. :+1:

**Comment by mariobehling** [comment]
Please resolve conflicts. Cheers.

**Comment by aashutoshrathi** [comment]
@mariobehling please check this, before I get more of conflicts.

**Comment by duttaditya18** [comment]
@aashutoshrathi Resolve merge conflicts. Then it is good to go.

**Comment by mariobehling** [comment]
Good job. I added it now already as there are over and over PRs. So, hope to merge quicker from now on. Cheers.

**Pull request closed without merging**
