### PR TITLE
Fix #352: Speakers images not horizontally aligned

### LINKED ISSUE #352: Speakers images not horizontally aligned
In the "Speakers" section, the first two images aren't horizontally aligned for browser's screen width b/w 638px & 767px

iss1

Browser: Chrome
OS: Windows 8.1

### PR DESCRIPTION
**Pull request by apooravc**
Fixes #352 

Preview:
iss2

### CODE REVIEW

**Comment by gautamjajoo** [comment]
@apooravc Can you give the preview link?

**Comment by apooravc** [comment]
@gautamjajoo Sure. https://apooravc.github.io/2018.fossasia.org/

**Comment by simsausaurabh** [comment]
@apooravc I don't see any error in alignment on website, please check again.

**Comment by apooravc** [comment]
@simsausaurabh I checked again, the misalignment is there https://2018.fossasia.org/ when I decrease my browser screen width below 767px. Could you please check again?

**Comment by simsausaurabh** [comment]
Yeah I got it now, there is alignment error.
And there is more alignment issue after speaker: Vigneshwer Dhinakaran. At same width mentioned above.

screenshot from 2018-01-28 19-00-31

**Comment by apooravc** [comment]
@simsausaurabh I see. Should I create another issue for that or try solving it within this thread itself?

**Comment by simsausaurabh** [comment]
There isn't any much changes made, and since both of these reference the alignment of speakers in small browser screen. So I guess you can do it in this same PR.

**Comment by apooravc** [comment]
@simsausaurabh Done. Could you please review? https://apooravc.github.io/2018.fossasia.org/

**Comment by mariobehling** [comment]
Please dont fix this in the CSS. Simply take out empty lines. Please recommit once done.

**Comment by apooravc** [comment]
@mariobehling Could you please explain the "take out empty lines" part? I didn't get it.

**Pull request closed without merging**
