### PR TITLE
Fixed #176

### LINKED ISSUE #176: Add missing speakers
Ben Sadeghi
Truc Viet Le
Jollen Chen
Kenji Shimono

Jayaditya Gupta
Dr Chong Shang Shan
Darin Lobo
Mishari Muqbil

### PR DESCRIPTION
**Pull request by achiv**
Added 8 Speakers

<a href="https://achiv.github.io/2018.fossasia.org/">Preview Link</a>

### CODE REVIEW

**Comment by hpdang** [comment]
@achiv please resolve the conflict

**Comment by achiv** [comment]
@hpdang Conflict resolved

**Comment by hpdang** [comment]
@achiv wrong profile URL for Mishari Muqbil, please update

**Comment by achiv** [comment]
@hpdang Corrected the URL links

**Comment by hpdang** [comment]
great, thanks @achiv

**Pull request merged**
