### PR TITLE
Fixed #362 , #368 and #369

### LINKED ISSUE #362: Add speakers Ajo Robert, Nam Nguyen Hoai, Dai Dang Van
Please take their info from here: https://eventyay.com/e/b548bcfc/#speakers

Photos:
Ajo Robert
134070_10151234684126941_606074026_o

Nam Nguyen Hoai
anh

Dai Dang Van
21231568_797793653734127_3347141000639258194_n

### PR DESCRIPTION
**Pull request by dishant-sheth**
Fixed #362 - Add speakers Ajo Robert, Nam Nguyen Hoai, Dai Dang Van , 
#368 - Replace speaker photos Jackson Isaac, Aravind Putrevu & Dipesh Chander Monga 
and #369 - Add missing job title for Pooja Purswani, Benjamin Scherrey & Jackson Isaac. 
Preview Link - https://dishant-sheth.github.io/2018.fossasia.org/

### CODE REVIEW

**Comment by dishant-sheth** [comment]
Do check if it's alright now. The given image of Aravind Putrevu has very odd dimensions. So, I have simply cropped the image to achieve the 300*300 dimensions.

**Comment by dishant-sheth** [comment]
I have made the necessary changes. @mariobehling

**Comment by gautamjajoo** [comment]
@dishant-sheth Please resolve the conflicts.

**Comment by edenyay** [comment]
What happened to Tiejun Chen & Jackson Isaac? Please check again

**Comment by dishant-sheth** [comment]
Changes made as required !

**Comment by mariobehling** [comment]
Thanks, but please avoid PNG as it is usally bigger than JPG. Merging this as work in progress. Cheers.

**Comment by duttaditya18** [comment]
@dishant-sheth Yes. Use JPGs for realistic images and photos.

**Comment by dishant-sheth** [comment]
Sure. Thank you !

**Pull request merged**
