### PR TITLE
Updated Speaker's Bio - Felipe Hoffa

### LINKED ISSUE #107: Update Speaker's Bio - Felipe Hoffa
Under Featured Speakers Session: 

Please remove the current bio of Felipe Hoffa and add the following text: 

In 2011 Felipe Hoffa moved from Chile to San Francisco to join Google as a Software Engineer. Since 2013 he's been a Developer Advocate on big data - to inspire developers around the world to leverage the Google Cloud Platform tools to analyze and understand their data in ways they could never before. You can find him in several YouTube videos, blog posts, and conferences around the world.

### PR DESCRIPTION
**Pull request by duttaditya18**
* Updated Speaker's Bio of Felipe Hoffa
* Properly aligned
* Fixes #107 

**Preview Link :** https://duttaditya18.github.io/2018.fossasia.org/

### CODE REVIEW

**Comment by himanish-star** [comment]
@duttaditya18 , This decreases the font size eventually

**Comment by duttaditya18** [comment]
@himanish-star Yes. But I did not mess around with spacing.

**Comment by himanish-star** [comment]
@duttaditya18 neither did I. you can check my changes at https://himanish-star.github.io/2018.fossasia.org/ it works . I'm trying to figure out why it's going wrong at the main site.

**Comment by duttaditya18** [comment]
@himanish-star You put too much margin on every single speaker div.

**Comment by hpdang** [comment]
@duttaditya18 agree, too much margin space, let's shorten the text which cld be a neutral solution. Remove the last sentence 'You can find ...'. Thanks guys for the feedback :)

**Comment by duttaditya18** [comment]
@hpdang Done.

**Comment by duttaditya18** [comment]
Please check it out!

**Pull request merged**
