### PR TITLE
Remove Speaker Giannis Konstantinidis #399

### PR DESCRIPTION
**Pull request by iknoorjobs**

### CODE REVIEW

**Comment by gautamjajoo** [comment]
Hey!! as you are new to organization. Always claim issues first and don't ask and don't send PRs for already claimed issues . 
No problem for now, but remember from next time. :)

**Comment by iknoorjobs** [comment]
@gautamjajoo Okay. Thanks

**Comment by nityanandagohain** [comment]
@iknoorjobs Please read fossasia's best practices and use special keywords while sending a PR so that it's easier for the maintainer's. Also since you are removing Giannis you can delete his picture from images.

**Comment by gautamjajoo** [comment]
@nityanandagohain He has removed the picture!

**Comment by nityanandagohain** [comment]
yup sorry! i didn't see that 😃

**Comment by mariobehling** [comment]
I see some unrelated changes here. Giannis is removed now. Thanks for starting to contribute. Keep it up!

**Pull request closed without merging**
