### PR TITLE
Fixed #112: Added link to Map marker

### LINKED ISSUE #112: Map marker
It doesn't have a link whereas it should have a location added

### PR DESCRIPTION
**Pull request by samyakbvs**
The Map Marker didn't have a link but I added the location that is following to it

### CODE REVIEW

**Comment by samyakbvs** [comment]
test link - https://samyakbvs.github.io/samyakjainbvs-2018.fossasia.org/

**Comment by samyakbvs** [comment]
As some of the mentors told me that the link would be better on the address text rather than the icon, so I am changing it

**Comment by samyakbvs** [comment]
So what?

**Comment by samyakbvs** [comment]
I can't find any error in that case

**Comment by mariobehling** [comment]
Please keep the links in the same color as before. Only change to white underline same as email address above.

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/sam-yak-jainbvs-2018.fossasia.org/

**Comment by samyakbvs** [comment]
Color changed @vaibhavsingh97

**Comment by samyakbvs** [comment]
@mariobehling  pls merge

**Comment by samyakbvs** [comment]
It is in the same color @mariobehling

**Comment by samyakbvs** [comment]
This color was recommmended to me by one of the mentors

**Comment by vaibhavsingh97** [comment]
@samyakbvs Please change as what @mariobehling suggested.

**Comment by samyakbvs** [comment]
Changes made @mariobehling and @vaibhavsingh97

**Comment by samyakbvs** [comment]
https://samyakbvs.github.io/s-a-m-yak-jainbvs-2018.fossasia.org/

**Comment by samyakbvs** [comment]
@ParthS007 pls merge

**Comment by duttaditya18** [comment]
a

**Comment by samyakbvs** [comment]
@mariobehling pls merge

**Pull request closed without merging**
