### PR TITLE
github url has added and better quality image added

### PR DESCRIPTION
**Pull request by chetkhatri**
What were proposed in this Pull Request ?
* As suggested, Image quality was bad so it has been removed and nice quality image has been added.
* Github URL has been added.
How this pull request has tested ?
Manually, URL: https://chetkhatri.github.io/2018.fossasia.org/

### CODE REVIEW

**Comment by chetkhatri** [comment]
Reviewer added: @geekyd @hpdang

**Comment by edenyay** [comment]
hi @chetkhatri what do you think about current photo on https://2018.fossasia.org. it looks quite good now

**Comment by mariobehling** [comment]
Ok, thanks more serious photo. Cheers.

**Comment by chetkhatri** [comment]
@mariobehling Thank you !
@edenyay It was selfi ! with bag. So i took different one for #FOSSASIA  :+1:

**Comment by edenyay** [comment]
@chetkhatri thank you!

**Pull request merged**
