### PR TITLE
Add Stephanie Taylor #211

### PR DESCRIPTION
**Pull request by achiv**
Added another speaker

<a href= "https://achiv.github.io/2018.fossasia.org/">Preview lInk</a>

### CODE REVIEW

**Comment by hpdang** [comment]
@achiv please resolve conflict

**Comment by achiv** [comment]
@hpdang Conflict Resolved

**Comment by hpdang** [comment]
@achiv cld you also add her LinkedIn? https://www.linkedin.com/in/stephaniertaylor

**Comment by achiv** [comment]
@hpdang 
Added her linkedin profile.
Please have a look.

**Comment by hpdang** [comment]
thanks :+1:

**Pull request merged**
