### PR TITLE
Prevent hover overflow

### LINKED ISSUE #49: Overflow on hover
I just noticed that the team section, when viewed on mobile screens and smaller screens has an overflow issue. The semi-transparent div that flows in has a size larger than the image!

### PR DESCRIPTION
**Pull request by parimatrix**
Fixes #49 
@niccokunzmann @mariobehling

### CODE REVIEW

**Comment by parimatrix** [comment]
Can someone please help me get to know why the travis build fails?

**Comment by niccokunzmann** [comment]
Travis always fails. It does not test anything.

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
I have no write access so I can not do anything.

**Comment by heysadboy** [comment]
@niccokunzmann It's because there's no .travis.yml file in the repo. I think we should add it as the default file is of another type. It says 'Could not find .travis.yml, using standard configuration.'.

**Comment by niccokunzmann** [comment]
You can create an issue describing the problem and proposing a solution.

**Comment by heysadboy** [comment]
@niccokunzmann Sure!

**Comment by parimatrix** [comment]
@niccokunzmann Sorry for the wrong tag! Will wait for someone to have a look at the PR.

**Comment by niccokunzmann** [comment]
No problem. I just lost them and realized it^^

**Pull request merged**
