### PR TITLE
Back to Top button

### PR DESCRIPTION
**Pull request by Aakash-DD**
When the user clicks on the button, take to the top of the document.

### CODE REVIEW

**Comment by duttaditya18** [comment]
@Aakash-DD Please give a preview link from now on. Here is it anyway : https://rawgit.com/Aakash-DD/2018.fossasia.org/master/index.html

**Comment by Aakash-DD** [comment]
I have made some changes now it will work fine.

**Comment by mariobehling** [comment]
Thank you. Good start, but please open an issue first and use the existing JS features for in-page links.

**Comment by Aakash-DD** [comment]
Added an Arrow pointing-UP instead of Text ("TOP").

**Comment by NengakDakup** [comment]
The back to top button should have a scrolling effect... What do you think??

**Comment by duttaditya18** [comment]
@NengakDakup Was thinking the same thing. But improvements can be made later. If this isn't merged, adding a Back to Top button would be stalled.

**Comment by Aakash-DD** [comment]
@NengakDakup  if you add link in the top button then it will again reload and increase time complexity and loading of the page

**Comment by mariobehling** [comment]
Closing due to inactivity. Please open a new PR if you would like to follow up.

**Pull request closed without merging**
