### PR TITLE
Swapped the Position Keya and Preetam

### LINKED ISSUE #224: Swap speakers'positions Preetam Rai >< Keya Desai
Photo of Keya Desai should be where Preetam Rai is now and vice versa

### PR DESCRIPTION
**Pull request by gautamjajoo**
Fixes #224 and #220

### CODE REVIEW

**Comment by simsausaurabh** [comment]
Please provide deployment link in every PR so that the review can be done easily.

**Comment by gautamjajoo** [comment]
@simsausaurabh I have been doing in some of them. The main problem is that I have been commiting on different branches and github.io supports only master.

**Comment by hpdang** [comment]
@gautamjajoo please figure out how to set up a preview page first before claiming a new issue, it is a common practice that you provide a preview link

**Comment by gautamjajoo** [comment]
https://pseudocoders.github.io/gautamfossasia/
@hpdang

**Pull request merged**
