### PR TITLE
Change color of text on button:

### PR DESCRIPTION
**Pull request by mani87**
Color of the link/text on the
button changed to white to make
it visible.

Closes https://github.com/fossasia/2018.fossasia.org/issues/31

### CODE REVIEW

**Comment by mani87** [comment]
@AshishkrGoyal that means Pr created by me is waste? :(

**Comment by AshishkrGoyal** [comment]
@mani87 
it will be decided by the developers who have write access to this repo.

nothing is waste in open source, you will learn something new always

cheers 👍

**Comment by niccokunzmann** [comment]
@AshishkrGoyal Thanks for voting for @mani87's Solution!

**Comment by mani87** [comment]
@niccokunzmann and @AshishkrGoyal thankyou guys! :)

**Pull request merged**
