### PR TITLE
Add Exhibitors Info

### LINKED ISSUE #520: Add exhibitors info into exhibition page
The exhibition page info of exhibitors is here: https://2018.fossasia.org/exhibition/#exhibitors

Please add the exhibitors info into the section using the information here: https://docs.google.com/spreadsheets/d/1J-SkUAgp7HtcLEm92Iyg4dq_jpe6CrbPDaiCF3IkJ-4/edit#gid=0

### PR DESCRIPTION
**Pull request by PrP-11**
Fixes #520

### CODE REVIEW

**Comment by PrP-11** [comment]
ex1
ex2
ex3
ex4

**Comment by PrP-11** [comment]
@mariobehling Please review

**Comment by duttaditya18** [comment]
Please provide a Preview Link from now on.

Here it is anyway : https://rawgit.com/PrP-11/2018.fossasia.org/b2/exhibition/index.html

**Comment by mariobehling** [comment]
Thank you. I am merging this as work in progress. Cheers.

**Pull request merged**
