### PR TITLE
Fixes #274 : Correct indentation

### LINKED ISSUE #274: Correct the indentation and make it uniform
Correct the indentation on the index page

**Working on it**

### PR DESCRIPTION
**Pull request by akshatnitd**
Fixes #274 
Also, make the coding pattern uniform

**Preview link** : https://akshatnitd.github.io/2018.fossasia.org/

Made changes to the code indentation in the `index.html` file to improve code quality.

### CODE REVIEW

**Comment by akshatnitd** [comment]
@hpdang Please review :)

**Comment by realslimshanky** [comment]
Please mention the issue no which you are trying to solve.

**Comment by akshatnitd** [comment]
It is already mentioned in the commit title, as well as the PR title.
Issue #274

**Comment by realslimshanky** [comment]
When you add issue no in the commit, the atomic commit gets referenced on the issue. When you reference issue no in the description the PR gets referenced to the issue which is more developer friendly. :blush:

**Comment by akshatnitd** [comment]
@realslimshanky Okay. Got to learn a new thing :)

**Comment by realslimshanky** [comment]
@akshatnitd awesome. That's the beauty of open source right! :tada:

**Comment by gautamjajoo** [comment]
@akshatnitd Please resolve the conflicts.

**Comment by akshatnitd** [comment]
@mariobehling @achiv Please review :)

**Comment by mariobehling** [comment]
Please help to make it easier for reviewers. Provide a test site and point out exactly what you changed.

**Comment by akshatnitd** [comment]
**Preview link** : https://akshatnitd.github.io/2018.fossasia.org/

Made changes to the code indentation in the `index.html` file to improve code quality.

**Pull request merged**
