### PR TITLE
Fixes #134 : Added FOSSAIA's Company LinkedIn link, Added missing social links!

### LINKED ISSUE #134: Add LinkedIn Profiles for FOSSASIA, Add missing social links
> In the `index.html`, the codebase contains a line : `<!-- <a href="#"><i class="icon social_linkedin"></i></a> -->`
* Add the LinkedIn company link.

* Add missing social links

### PR DESCRIPTION
**Pull request by 0x48piraj**
# Fixes #134

* **_Added @fossasia company link, as it was commented in the codebase :wink:_** 
- _In the head_
- _In the body_

Added Details : 

- **arynchoong**
- **robertbobreyes**
- **libedinskylab**

**_Preview link - https://0x48piraj.github.io/2018.fossasia.org_**

### CODE REVIEW

**Comment by 0x48piraj** [comment]
@sayak119 Sorry, I forgot to turn github pages on :worried: 

It's Live now : _**https://0x48piraj.github.io/2018.fossasia.org/**_

**Comment by 0x48piraj** [comment]
Ping @mariobehling @hpdang :100:

**Comment by samyakbvs** [comment]
You mentioned in #118 that this PR is clean but I can see that this PR still has conflicts that are to be resolved

**Comment by 0x48piraj** [comment]
If @mariobehling will revert your changes, this PR will be merge capable :100:

**Comment by mariobehling** [comment]
I fixed some of the earlier issues. Please provide an updated PR resolving conflicts. Revert of earlier commits is no longer easily possible.

**Comment by 0x48piraj** [comment]
Okay. Just sending a fresh PR. Hold on please :blush:

**Comment by 0x48piraj** [comment]
CLosing and opening a new PR.

**Comment by 0x48piraj** [comment]
@mariobehling #139 :100:

**Pull request closed without merging**
