### PR TITLE
Improved social links display. Fixes #161 and #163

### LINKED ISSUE #112: Map marker
It doesn't have a link whereas it should have a location added

### LINKED ISSUE #161: Not proper space in between Social Icons
whatsapp image 2018-01-15 at 7 07 19 pm

### PR DESCRIPTION
**Pull request by Tanuj9043**
The social links display on small screens has also been improved.

Social Links :- 
a
b

Link :- 
https://tanuj9043.github.io/2018.fossasia.org/

### CODE REVIEW

**Comment by Tanuj9043** [comment]
I have squashed my commits and removed the map marker. Also the social links in navbar were meant to be hidden on smaller screen sizes but only github link was hiding. I added the class to other links too. Now, on smaller screen sizes, links can be accessed by navbar toggle.

Link :-
https://tanuj9043.github.io/2018.fossasia.org/

**Comment by Tanuj9043** [comment]
Could someone review these changes? @simsausaurabh ?

**Comment by simsausaurabh** [comment]
Please resolve the confilcts below: image not found, speakers been duplicated and not aligned properly. Also squash the commits.
screenshot from 2018-01-19 13-21-29
screenshot from 2018-01-19 13-22-03


And this is what I am getting when opening website in small screen - issue: 161 not solved properly.
screenshot from 2018-01-19 13-29-14

**Comment by Tanuj9043** [comment]
Okay. I will solve the issues. Thanks for reviewing.

**Pull request closed without merging**
