### PR TITLE
Add speaker Saurabh Jain

### PR DESCRIPTION
**Pull request by saurabhjn76**
**Changes:** added speaker Saurabh Jain

**Screenshot for the change**

screen shot 2018-02-15 at 11 10 37 am

### CODE REVIEW

**Comment by hpdang** [comment]
@saurabhjn76 do you have something that shows your full face? (not covering with your hand)

**Comment by saurabhjn76** [comment]
@hpdang Please review

**Comment by hpdang** [comment]
@saurabhjn76 this is wrongly scale, can you keep the ratio of the original image?

**Comment by saurabhjn76** [comment]
@hpdang Please review

**Comment by hpdang** [comment]
great! thanks

**Pull request merged**
