### PR TITLE
Chris Aniszczyk duplicate photo removed from speakers

### LINKED ISSUE #167: Remove duplicated speaker's photo
The speaker Chris Aniszczyk is listed as featured speaker (as in this photo here) screen shot 2018-01-17 at 01 09 22

But there is another photo of him in the other speaker section. Please help me remove his second photo in the normal speaker section. His photo and bio should be at the featured speaker section only. 
screen shot 2018-01-17 at 01 10 02

### PR DESCRIPTION
**Pull request by nityanandagohain**
fixes #167

### CODE REVIEW

**Comment by hpdang** [comment]
@nityanandagohain could you provide preview link? Thanks

**Comment by nityanandagohain** [comment]
How do I do that . will screen-shot be ok?

**Comment by nityanandagohain** [comment]
@hpdang 

Before
screenshot from 2018-01-17 22-24-59

After
screenshot from 2018-01-17 22-24-31

**Comment by simsausaurabh** [comment]
Use github gh-pages for deploying your forked repo and provide the generated link here. 
Refer this: https://pages.github.com/

**Comment by nityanandagohain** [comment]
But how to deploy the newbranch @simsausaurabh

**Pull request closed without merging**
