### PR TITLE
Fixed #237: 'Replace current speakers' photos with better quality ones'

### LINKED ISSUE #237: Replace current speakers' photos with better quality ones
Hi, some current photos didn't meet our standard of professionalism. Please help me replace them with the new photos as in the attachments. Thank you. 

1. Jollen Chen. 
jollen

3. Thia Kai Xin
kaixin_strata

4. Stepan Goncharov

5. Gilles Gravier 
gilles-gravier-foto 256x256

6. Martin Bähr
matinbahr_69

7. Ilya Verbitskiy
ilya

### PR DESCRIPTION
**Pull request by simsausaurabh**
Fixes: #237 
Deployment link: https://simsausaurabh.github.io/2018.fossasia.org/
@hpdang Please preview.

### CODE REVIEW

**Comment by mariobehling** [comment]
Please in future state what exactly your are changing. Thanks

**Comment by simsausaurabh** [comment]
Sorry, for the trouble I will clearly state the changes from next time. Thank you for the review. :smile:

**Comment by edenyay** [comment]
@simsausaurabh i haven't seen the updated version on our website yet. Could you check again? Thank you.

**Comment by simsausaurabh** [comment]
I have already merged the updateimages branch in master branch, the results are updated in my preview link and the changes from updateimages branch are already merged into 2018.fossasia.org:master. If it's not showing the I shall make PR again from my master branch. @edenyay thank you.

**Comment by simsausaurabh** [comment]
Please clear cache of your web browser it's problem with the stored cache.
Thank you. @edenyay

**Pull request merged**
