### PR TITLE
Added the dark overlay

### LINKED ISSUE #513: Make a darker overlay on top slider
It looks like the white font is a bit difficult to see. Please make a darker overlay on the top slider to make the font more easily readable.

screenshot from 2018-03-01 23-50-08

### PR DESCRIPTION
**Pull request by abhishek71994**
sorry about the other files but they are checked in the other pr.

This pr resolves #513

### CODE REVIEW

**Comment by abhishek71994** [comment]
I've made the changes, kindly check @mariobehling

**Comment by mariobehling** [comment]
Please provide a test deployment.

**Comment by abhishek71994** [comment]
https://rawgit.com/abhishek71994/2018.fossasia.org/master/index.html

Here you go.

**Comment by mariobehling** [comment]
screenshot from 2018-03-12 04-47-52


Thank you. It turns out the contrast between different red colors does not work well. Please change the overlay using black similar to the other overlay area on the same page below.

**Comment by abhishek71994** [comment]
added the proposed black overlay

**Comment by mariobehling** [comment]
Thanks. Actually this issue seems to have been solved recently by another PR. Please also check that you only make changes that are related to the specific issue in future. Cheers! Keep it up.

**Pull request closed without merging**
