### PR TITLE
Added Speakers

### LINKED ISSUE #88: Add confirmed speakers to "Speakers Section" same as 2017
There are confirmed speakers for 2018 up now: https://eventyay.com/e/b548bcfc/

Reuse existing images in the folder `/img`

Please add them into a section "Speakers" same as in previous year.

screenshot from 2017-12-06 11-02-51

### PR DESCRIPTION
**Pull request by duttaditya18**
* Added Speakers and Featured Speakers from https://eventyay.com/e/b548bcfc/
* Added images of Speakers note there in `img/`
* Added Social Links and info of Speakers
* Fixes #88

**Here is a live link :** https://duttaditya18.github.io/2018.fossasia.org/
Take a look @mariobehling @fossasia/web-developers @fossasia/website-admins

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Please avoid the spaces below speaker photos, name, and organization.

**Comment by duttaditya18** [comment]
@mariobehling What exactly?

**Comment by duttaditya18** [comment]
@mariobehling Fixed!

**Comment by duttaditya18** [comment]
@mariobehling Merge?

**Comment by mariobehling** [comment]
Thanks!

**Pull request merged**
