### PR TITLE
Improved Image quality of Speakers

### PR DESCRIPTION
**Pull request by gautamjajoo**
Fixes most of the #247 . @mariobehling

### CODE REVIEW

**Comment by gautamjajoo** [comment]
https://gautamjajoo.github.io/fossasia2018/
Preview

**Comment by hpdang** [comment]
@gautamjajoo please use the portrait of Alisha

image1 1

**Comment by gautamjajoo** [comment]
@mariobehling Done the changes!

**Comment by gautamjajoo** [comment]
@hpdang Please review.

**Pull request merged**
