### PR TITLE
Fix #141: Minor issues on index page

### LINKED ISSUE #141: Minor issues on index page
Discovered some minor issues when working on the Speakers Information:

- The reference link for the event schedule is still directing to the year 2017 schedule.
image
- The starting time for the exhibition program is wrong.
image
- Copyright year - Should be 2018 instead
image

### PR DESCRIPTION
**Pull request by mengjiann**

### CODE REVIEW

**Comment by mariobehling** [comment]
Missing related issue and description. I don't know what the issue is. Please follow up according to best practices. Therefore closing it now.

**Comment by mengjiann** [comment]
To fix #141 .

ping @mariobehling

**Comment by hpdang** [comment]
@mengjiann seems therer conflicts, can you look into it?

**Comment by mengjiann** [comment]
Please ignore this PR. The latest merge wasnt done properly.

**Pull request closed without merging**
