### PR TITLE
Adds 8 speakers

### LINKED ISSUE #145: Add missing speakers
Speakers are not completed added from https://eventyay.com/e/b548bcfc/#speakers
Add:
- [ ] Kiruthika Ramanathan
- [ ] Andrew Lee
- [ ] Héctor Orón Martínez
- [ ] Seth Vargo

### PR DESCRIPTION
**Pull request by abishekvashok**
Adds 8 speakers to the 2018 summit site
Fixes #145
Live preview: https://abishekvashok.github.io/2018.fossasia.org/

### CODE REVIEW

**Comment by hpdang** [comment]
@abishekvashok please resolve the conflict and do the following please: 

* Replace the picture of MishariMuqbil with this new one https://plus.google.com/photos/117037994337793091867/albums/profile/5634090050364661954?iso=false

* Take out Robert Foss

**Comment by abishekvashok** [comment]
@hpdang on the way

**Comment by hpdang** [comment]
@abishekvashok can you fix the conflict?

**Comment by abishekvashok** [comment]
@hpdang done

**Comment by hpdang** [comment]
hi guys, I am closing this PR to avoid confusion. There are some new updates. Check out if you want to help at other issues https://github.com/fossasia/2018.fossasia.org/issues. Thank you all.

**Pull request closed without merging**
