### PR TITLE
Fixes #127. Event Partner Social profiles

### LINKED ISSUE #127: Add 1/2 more social profiles of event Partners
Add more social profiles of vent partners under event partner section

### PR DESCRIPTION
**Pull request by arjunpandey2003**
Fixes #127 
Update index.html

### CODE REVIEW

**Comment by arjunpandey2003** [comment]
https://arjunpandey2003.github.io/2018.fossasia.org/

**Comment by arjunpandey2003** [comment]
There was some problem, everything was right i even check the icon css file, just replaced the icon and link

**Comment by arjunpandey2003** [comment]
@sayak119

**Comment by arjunpandey2003** [comment]
@mariobehling pls review

**Comment by mariobehling** [comment]
Thanks.

**Comment by arjunpandey2003** [comment]
Welcome

**Pull request merged**
