### PR TITLE
Bug fix: display links in venue section

### PR DESCRIPTION
**Pull request by prakamya-mishra**
There was an issue in the venue section in which some text was not getting displayed due to missing span which i have fixed.
Before:
screen shot 2017-09-20 at 7 42 40 pm
After:
screen shot 2017-09-20 at 7 42 53 pm

### CODE REVIEW

**Comment by prakamya-mishra** [comment]
@mariobehling Can you please take a look over it?

**Comment by hpdang** [comment]
Even with small issues, please help to make it easier for everyone and follow best practices. This will ensure everyone is aligned also for bigger issues. Open issues first and provide a test page.

**Comment by prakamya-mishra** [comment]
Ok 
Sorry I will keep this in mind for the next time...what should I do know?

**Comment by hpdang** [comment]
Read best practices and follow them: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by prakamya-mishra** [comment]
I have added issue #64 .

**Comment by prakamya-mishra** [comment]
Is there a problem now also?

**Comment by mariobehling** [comment]
Please provide a test page.

**Comment by prakamya-mishra** [comment]
Sorry but i dont know what is a test page can you explain?

**Comment by mariobehling** [comment]
Talk with the community here https://gitter.im/fossasia/fossasia

**Pull request merged**
